# Generated by Django 3.1.7 on 2021-03-22 00:37
import os
import csv
from django.db import migrations
from django.conf import settings

CVE = 0
CVSS = 1
CWE_CODE = 2
CWE_NAME = 3

def add_vulnerabilities(apps,schema_editor):
    Vulnerability = apps.get_model('cve_chart', 'Vulnerability')
    cwe_dataset_file = os.path.join(settings.BASE_DIR, 'cve.csv')
    with open(cwe_dataset_file) as dataset:
        reader = csv.reader(dataset)
        next(reader) # ignora prima linie
        for entry in reader:
            cve = ''
            if entry[CVE]:
                cve = str(entry[CVE])
            cvss = 0.0
            if entry[CVSS]:
                cvss = float(entry[CVSS])
            cwe_code = ''
            if entry[CWE_CODE]:
                cwe_code = str(entry[CWE_CODE])
            cwe_name = ''
            if entry[CWE_NAME]:
                cwe_name = str(entry[CWE_NAME])

            Vulnerability.objects.create(
                cve = cve,
                cvss = cvss,
                cwe_code = cwe_code,
                cwe_name = cwe_name,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('cve_chart', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_vulnerabilities),
    ]
